"""Create GuildSettings model

Revision ID: b9e8cd620367
Revises: 0d22031fe40e
Create Date: 2023-08-03 18:43:28.406562

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = "b9e8cd620367"
down_revision = "0d22031fe40e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guildsettings",
        sa.Column("allowed_domains", sa.String(), nullable=True),
        sa.Column("guild_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "verified_role_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "verification_log_channel_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guildsettings")
    # ### end Alembic commands ###
